# Generated by Django 5.0.1 on 2024-02-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_phone_post_author_rename_name_post_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=130, unique=True),
        ),
    ]
