# Generated by Django 5.0.1 on 2024-02-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.CharField(blank=True, max_length=130, unique=True),
        ),
    ]
