# Generated by Django 5.0.1 on 2024-04-04 03:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_campaigncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
