# Generated by Django 5.0.1 on 2024-04-16 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_campaign_image'),
        ('volunteers', '0004_volunteerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='volunteers.category'),
        ),
    ]
