# Generated by Django 5.0.1 on 2024-03-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_donor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_organization',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('donor', 'Donor'), ('organization', 'Organization')], max_length=15, null=True),
        ),
    ]
