# Generated by Django 5.0.1 on 2024-03-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_donor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('donor', 'Donor'), ('organization', 'Organization'), ('employee', 'employee')], max_length=15, null=True),
        ),
    ]
