# Generated by Django 5.0.1 on 2024-04-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
    ]
